## What is NumPy?
NumPy stands for Numerical Python.
It is a powerful Python library used for performing mathematical and scientific calculations efficiently.
It mainly provides a multi-dimensional array object called ndarray (N-dimensional array).
NumPy arrays are faster, more compact, and more efficient than Python lists when you work with large amounts of data.

NumPy = Fast mathematical operations + Efficient data storage + Support for large multi-dimensional arrays

In [1]:
# import the library
import numpy as np

In [3]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
arr = np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(8,)

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr

In [18]:
arr[3]

np.int64(4)

In [19]:
arr[3].item()

4

In [20]:
arr[6] = 11

In [21]:
arr

array([ 1,  2,  3,  4,  5,  6, 11,  8])

In [27]:
arr[:5]

array([1, 2, 3, 4, 5])

In [30]:
arr[4:]

array([ 5,  6, 11,  8])

In [31]:
arr[:-1]

array([ 1,  2,  3,  4,  5,  6, 11])

In [32]:
arr[::-1]

array([ 8, 11,  6,  5,  4,  3,  2,  1])

In [33]:
arr[::-3]

array([8, 5, 2])

In [34]:
arr[::-2]

array([8, 6, 4, 2])

In [35]:
arr[:-2]

array([1, 2, 3, 4, 5, 6])

In [37]:
arr[3:6] 

array([4, 5, 6])

In [42]:
arr[0:6:2]

array([1, 3, 5])

In [6]:
lst1 = [1, 2, 3, 4, 5]
lst2 = [3, 4, 5, 6, 7]
lst3 = [5, 6, 7, 8, 9]
np.array([lst1, lst2, lst3])

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [9]:
arr1.shape

(3, 5)

In [7]:
arr1 = np.array([lst1, lst2, lst3])

In [43]:
arr1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [55]:
arr1[:,2]

array([3, 5, 7])

In [56]:
arr1[1:,2]

array([5, 7])

In [57]:
arr1[:,4]

array([5, 7, 9])

In [53]:
arr1[2:,4]

array([9])

In [62]:
arr1[:,0]

array([1, 3, 5])

In [65]:
arr1[1:,1:3]

array([[4, 5],
       [6, 7]])

In [74]:
arr1[1:,3:]

array([[6, 7],
       [8, 9]])

In [78]:
arr1[1:,3:].shape

(2, 2)

In [77]:
arr1[:,3:]

array([[4, 5],
       [6, 7],
       [8, 9]])

In [79]:
arr1[:,3:].shape

(3, 2)

In [90]:
# Exploratory Data Analysis(EDA)
arr

array([ 1,  2,  3,  4,  5,  6, 11,  8])

In [97]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False])

In [98]:
arr[arr<5]

array([1, 2, 3, 4])

In [99]:
arr1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [100]:
arr1.shape

(3, 5)

In [101]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 3],
       [4, 5, 6],
       [7, 5, 6],
       [7, 8, 9]])

In [104]:
# mechanism to create an array
np.arange(1,10,1)   #arange(start, stop, step)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.arange(1,10,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [108]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [120]:
np.arange(1,30,2).reshape(3,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [125]:
np.arange(1,30,2).reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [128]:
np.arange(1,30,2).reshape(3,5,1)    #3-D

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]],

       [[21],
        [23],
        [25],
        [27],
        [29]]])

In [129]:
arr

array([ 1,  2,  3,  4,  5,  6, 11,  8])

In [130]:
arr * arr

array([  1,   4,   9,  16,  25,  36, 121,  64])

In [131]:
arr1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [132]:
arr1 * 2

array([[ 2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14],
       [10, 12, 14, 16, 18]])

In [136]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [139]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [147]:
np.zeros_like((3,5))

array([0, 0])

In [160]:
np.random.randint(50,100,6)

array([70, 55, 82, 56, 78, 90], dtype=int32)

In [162]:
np.random.randint(50,100,6).reshape(3,2)

array([[50, 66],
       [70, 78],
       [84, 75]], dtype=int32)

In [165]:
np.random.randn(4,5)

array([[ 1.70186361,  1.46457217, -2.21442984,  0.16615695,  0.41638931],
       [-0.72239761, -1.29668356, -0.39655589,  2.0393689 ,  0.6276042 ],
       [ 0.65243103, -0.41686533, -0.30079601,  0.0252023 , -1.6253568 ],
       [ 1.13324804, -0.37763719, -0.66648805, -1.43719823,  1.60423048]])

In [166]:
np.random.random_sample((4,5))

array([[0.7844591 , 0.37342062, 0.11816785, 0.33666106, 0.90709509],
       [0.366049  , 0.98096366, 0.42985685, 0.76975835, 0.55137292],
       [0.63624836, 0.0784439 , 0.86154003, 0.22577226, 0.7176133 ],
       [0.67308958, 0.19779846, 0.39211764, 0.54639571, 0.61456183]])